services:
  - type: web
    name: financial-analyzer
    env: python
    region: frankfurt  # o la región que prefieras
    buildCommand: |
      # Instalar dependencias y construir el frontend
      cd frontend && npm install && npm run build
      # Instalar dependencias del backend
      cd ../backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0