name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade fastapi httpcore pandas pytest

    - name: Run tests
      run: |
        pytest

    - name: Clean up generated files
      run: |
        rm -rf assets/index-CMXX0eFc.js
